name: Build OpenWrt Firmware

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 10 * * 3' # 每周三北京时间18点（UTC时间10点）定时自动编译
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clean up old Actions runs
        run: |
          gh run list --limit 100 --json databaseId,status,conclusion | jq -r '.[] | select(.status=="completed") | select(.conclusion=="success") | .databaseId' | while read run_id; do gh run delete "$run_id" -y; done

      - name: Clean up old Releases
        run: |
          gh release list --limit 100 | awk '{print $1}' | while read release_id; do gh release delete "$release_id" -y; done

  build:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build OpenWrt Firmware
        run: |
          docker build -t openwrt-build .
          docker run --rm -v $(pwd)/output:/build/bin openwrt-build

      - name: Set Release Tag
        id: set_tag
        run: |
          TAG="${{ github.run_number }}-x86_64-$(date +'%Y%m%d')"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Upload firmware to releases
        uses: softprops/action-gh-release@v1
        with:
          files: output/*
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
